version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.3
    container_name: witproject-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - loki-network
  kafka:
    image: bitnami/kafka:3.6.1
    container_name: witproject-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - loki-network

  calculator:
    build:
      context: ./Calculator
      dockerfile: Dockerfile
    container_name: witproject-calculator
    ports:
      - "8083:8080"
      - "8086:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MANAGEMENT_SERVER_PORT=8081
    depends_on:
      - kafka
    networks:
      - loki-network

  rest:
    build:
      context: ./Rest
      dockerfile: Dockerfile
    container_name: witproject-rest
    ports:
      - "8084:8080"
      - "8085:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MANAGEMENT_SERVER_PORT=8081
    depends_on:
      - kafka
    networks:
      - loki-network

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: witproject-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - rest
    networks:
      - loki-network

  loki:
    image: grafana/loki:2.9.3
    container_name: witproject-loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config.yaml
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:10.2.3
    container_name: witproject-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - loki-network

volumes:
  zookeeper-data:
  kafka-data:
  prometheus-data:
  grafana-data:
  loki-data:

networks:
    loki-network:
      driver: bridge