global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'witproject-rest'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['witproject-rest:8081']

  - job_name: 'witproject-calculator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['witproject-calculator:8081']