scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['witproject-prometheus:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['witproject-loki:3100']

  - job_name: 'calculator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['witproject-calculator:8081']

  - job_name: 'rest'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['witproject-rest:8081']