server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: structured-logs
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "structured-logs"
          container_name: "witproject-calculator"
          __path__: /var/log/calculator/*.json
      - targets: ["localhost"]
        labels:
          job: "structured-logs"
          container_name: "witproject-rest"
          __path__: /var/log/rest/*.json
    pipeline_stages:
      - json:
          expressions:
            app_name: app_name
            requestId: request_id
            loglevel: level
            message: message
      - labels:
          app_name: ""
          requestId: ""
          loglevel: ""
          message: ""


  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container_name
    pipeline_stages:
      - json:
          expressions:
            app_name: app_name
            requestId: request_id
            loglevel: loglevel
            message: message
      - labels:
          app_name: ""
          requestId: ""
          loglevel: ""
          message: ""
